import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  BarChart3,
  Download,
  Users,
  Clock,
  TrendingUp,
  Calendar,
  RefreshCw,
  FileText,
} from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { useSupabaseAuth } from '@/hooks/useSupabaseAuth';
import { useSupabaseData } from '@/hooks/useSupabaseData';
import { supabase } from '@/integrations/supabase/client';

interface LiveReportsManagerProps {
  organisationId?: string;
  departmentId?: string;
}

interface EmployeeBreakdown {
  user_id: string;
  employee_name: string;
  total_hours: number;
  total_sessions: number;
  average_session_duration: number;
}

interface DailyBreakdown {
  date: string;
  total_hours: number;
  total_employees: number;
  total_sessions: number;
}

interface GeneratedReport {
  summary: {
    total_employees: number;
    total_hours_worked: number;
    average_hours_per_day: number;
    total_work_sessions: number;
  };
  employee_breakdown: EmployeeBreakdown[];
  daily_breakdown: DailyBreakdown[];
}

const calculateWorkedHours = (clockIn?: string | null, clockOut?: string | null) => {
  if (!clockIn || !clockOut) return 0;
  const diffMs = new Date(clockOut).getTime() - new Date(clockIn).getTime();
  if (diffMs <= 0) return 0;
  return diffMs / (1000 * 60 * 60);
};

export function LiveReportsManager({ organisationId, departmentId }: LiveReportsManagerProps) {
  const { toast } = useToast();
  const { profile } = useSupabaseAuth();
  const { profiles, timeLogs, loading: isDataLoading } = useSupabaseData();
  const [isLoading, setIsLoading] = useState(false);
  const [reportData, setReportData] = useState<GeneratedReport | null>(null);
  const [reportType, setReportType] = useState<'weekly' | 'monthly'>('weekly');
  const [lastGenerated, setLastGenerated] = useState<Date | null>(null);
  const hasAutoGeneratedRef = useRef(false);

  const scopedProfiles = useMemo(() => {
    if (!profile) return [];

    let result = profiles.filter((entry) => entry.is_active !== false);

    if (organisationId) {
      result = result.filter((entry) => entry.organisation_id === organisationId);
    } else if (profile.user_type === 'org_admin' && profile.organisation_id) {
      result = result.filter((entry) => entry.organisation_id === profile.organisation_id);
    }

    if (departmentId) {
      result = result.filter((entry) => entry.department_id === departmentId);
    } else if (profile.user_type === 'manager' && profile.department_id) {
      result = result.filter((entry) => entry.department_id === profile.department_id);
    }

    if (profile.user_type === 'employee') {
      result = result.filter((entry) => entry.user_id === profile.user_id);
    }

    return result;
  }, [profiles, profile, organisationId, departmentId]);

  const profileByUserId = useMemo(() => {
    return new Map(
      scopedProfiles
        .filter((entry) => !!entry.user_id)
        .map((entry) => [entry.user_id as string, entry])
    );
  }, [scopedProfiles]);

  const scopedUserIdSet = useMemo(() => {
    return new Set(
      scopedProfiles
        .map((entry) => entry.user_id)
        .filter((userId): userId is string => typeof userId === 'string' && userId.length > 0)
    );
  }, [scopedProfiles]);

  const scopedLogs = useMemo(() => {
    return timeLogs.filter((entry) => scopedUserIdSet.has(entry.user_id));
  }, [timeLogs, scopedUserIdSet]);

  const buildReport = (type: 'weekly' | 'monthly'): GeneratedReport => {
    const now = new Date();
    const periodStart = new Date(now);

    if (type === 'weekly') {
      periodStart.setHours(0, 0, 0, 0);
      periodStart.setDate(periodStart.getDate() - ((periodStart.getDay() + 6) % 7));
    } else {
      periodStart.setHours(0, 0, 0, 0);
      periodStart.setDate(1);
    }

    const logsInRange = scopedLogs.filter((entry) => {
      const logDate = new Date(entry.date);
      return logDate >= periodStart && logDate <= now && !!entry.clock_in && !!entry.clock_out;
    });

    const employeeMap = new Map<string, { name: string; hours: number; sessions: number }>();
    const dailyMap = new Map<string, { hours: number; sessions: number; users: Set<string> }>();

    for (const entry of logsInRange) {
      const workedHours = calculateWorkedHours(entry.clock_in, entry.clock_out);
      const person = profileByUserId.get(entry.user_id);
      const displayName = person?.display_name || person?.username || 'Unknown User';

      const employeePrev = employeeMap.get(entry.user_id) || {
        name: displayName,
        hours: 0,
        sessions: 0,
      };
      employeePrev.hours += workedHours;
      employeePrev.sessions += 1;
      employeeMap.set(entry.user_id, employeePrev);

      const dayKey = entry.date;
      const dailyPrev = dailyMap.get(dayKey) || { hours: 0, sessions: 0, users: new Set<string>() };
      dailyPrev.hours += workedHours;
      dailyPrev.sessions += 1;
      dailyPrev.users.add(entry.user_id);
      dailyMap.set(dayKey, dailyPrev);
    }

    const employeeBreakdown: EmployeeBreakdown[] = Array.from(employeeMap.entries())
      .map(([userId, summary]) => ({
        user_id: userId,
        employee_name: summary.name,
        total_hours: Math.round(summary.hours * 100) / 100,
        total_sessions: summary.sessions,
        average_session_duration:
          summary.sessions > 0 ? Math.round((summary.hours / summary.sessions) * 100) / 100 : 0,
      }))
      .sort((left, right) => right.total_hours - left.total_hours);

    const dailyBreakdown: DailyBreakdown[] = Array.from(dailyMap.entries())
      .map(([date, summary]) => ({
        date,
        total_hours: Math.round(summary.hours * 100) / 100,
        total_employees: summary.users.size,
        total_sessions: summary.sessions,
      }))
      .sort((left, right) => left.date.localeCompare(right.date));

    const totalHoursWorked = employeeBreakdown.reduce((total, entry) => total + entry.total_hours, 0);
    const totalWorkSessions = employeeBreakdown.reduce((total, entry) => total + entry.total_sessions, 0);
    const totalEmployees = employeeBreakdown.length;
    const averageHoursPerDay =
      dailyBreakdown.length > 0 ? Math.round((totalHoursWorked / dailyBreakdown.length) * 100) / 100 : 0;

    return {
      summary: {
        total_employees: totalEmployees,
        total_hours_worked: Math.round(totalHoursWorked * 100) / 100,
        average_hours_per_day: averageHoursPerDay,
        total_work_sessions: totalWorkSessions,
      },
      employee_breakdown: employeeBreakdown,
      daily_breakdown: dailyBreakdown,
    };
  };

  const generateReport = async (type: 'weekly' | 'monthly' = reportType) => {
    setIsLoading(true);
    try {
      const generated = buildReport(type);
      setReportData(generated);
      setLastGenerated(new Date());

      const today = new Date();
      const periodStart = new Date(today);
      if (type === 'weekly') {
        periodStart.setHours(0, 0, 0, 0);
        periodStart.setDate(periodStart.getDate() - ((periodStart.getDay() + 6) % 7));
      } else {
        periodStart.setHours(0, 0, 0, 0);
        periodStart.setDate(1);
      }

      const { error } = await supabase.from('reports').insert({
        report_type: type,
        organisation_id: organisationId || profile?.organisation_id || null,
        department_id: departmentId || profile?.department_id || null,
        generated_by: profile?.user_id || null,
        start_date: periodStart.toISOString().split('T')[0],
        end_date: today.toISOString().split('T')[0],
        data: generated,
      });

      if (error) {
        console.error('Failed to persist report:', error);
      }

      toast({
        title: "📊 Report Generated",
        description: `${type.charAt(0).toUpperCase() + type.slice(1)} report generated successfully`,
      });
    } catch (error) {
      console.error('Report generation error:', error);
      toast({
        title: "❌ Error",
        description: "Failed to generate report. Please try again.",
        variant: "destructive"
      });
    } finally {
      setIsLoading(false);
    }
  };

  const downloadReport = async () => {
    if (!reportData) return;
    
    try {
      // Convert report data to CSV format
      const csvData = generateCSVReport(reportData);
      const blob = new Blob([csvData], { type: 'text/csv' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `work-hours-report-${reportType}-${new Date().toISOString().split('T')[0]}.csv`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);

      toast({
        title: "⬇️ Download Started",
        description: "Report download has started",
      });
    } catch (error) {
      toast({
        title: "❌ Error",
        description: "Failed to download report",
        variant: "destructive"
      });
    }
  };

  const generateCSVReport = (data: any): string => {
    let csv = 'Employee Name,Total Hours,Total Sessions,Average Session Duration\n';
    
    data.employee_breakdown.forEach((employee: any) => {
      csv += `"${employee.employee_name}",${employee.total_hours},${employee.total_sessions},${employee.average_session_duration.toFixed(2)}\n`;
    });

    csv += '\n\nDaily Breakdown\n';
    csv += 'Date,Total Hours,Total Employees,Total Sessions\n';
    
    data.daily_breakdown.forEach((day: any) => {
      csv += `${day.date},${day.total_hours},${day.total_employees},${day.total_sessions}\n`;
    });

    return csv;
  };

  const scheduleAutomatedReports = async () => {
    try {
      const recipients = scopedProfiles
        .filter((entry) => ['manager', 'org_admin', 'super_admin'].includes(entry.user_type))
        .map((entry) => entry.id)
        .filter((id): id is number => typeof id === 'number' && Number.isFinite(id));
      const uniqueRecipients = [...new Set(recipients)];

      if (uniqueRecipients.length === 0 && typeof profile?.id === 'number') {
        uniqueRecipients.push(profile.id);
      }

      if (uniqueRecipients.length === 0) {
        toast({
          title: "⚠️ No Recipients",
          description: "No eligible recipients found in your scope.",
          variant: "destructive"
        });
        return;
      }

      const rows = uniqueRecipients.map((profileId) => ({
        user_id: profileId,
        type: 'report_schedule',
        title: 'Automated Reports Scheduled',
        message: `${reportType.charAt(0).toUpperCase() + reportType.slice(1)} reports are now scheduled for your scope.`,
        data: {
          report_type: reportType,
          scheduled_by: profile?.user_id || null,
          organisation_id: organisationId || profile?.organisation_id || null,
          department_id: departmentId || profile?.department_id || null,
        },
        is_read: false,
        sent_via: ['in_app'],
      }));

      const { error } = await supabase.from('notifications').insert(rows);
      if (error) throw error;

      toast({
        title: "⏰ Automation Enabled",
        description: `Automated reports scheduled for ${uniqueRecipients.length} recipient${uniqueRecipients.length === 1 ? '' : 's'}.`,
      });
    } catch (error) {
      toast({
        title: "❌ Error",
        description: "Failed to schedule automated reports.",
        variant: "destructive"
      });
    }
  };

  useEffect(() => {
    if (isDataLoading || hasAutoGeneratedRef.current) return;
    hasAutoGeneratedRef.current = true;
    void generateReport('weekly');
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isDataLoading, scopedProfiles.length, scopedLogs.length]);

  return (
    <div className="space-y-6">
      
      {/* Report Controls */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <BarChart3 className="w-5 h-5" />
            Live Work Hours Analytics
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex flex-wrap gap-3 mb-4">
            <Button
              variant={reportType === 'weekly' ? 'default' : 'outline'}
              onClick={() => setReportType('weekly')}
              size="sm"
            >
              <Calendar className="w-4 h-4 mr-2" />
              Weekly Report
            </Button>
            
            <Button
              variant={reportType === 'monthly' ? 'default' : 'outline'}
              onClick={() => setReportType('monthly')}
              size="sm"
            >
              <Calendar className="w-4 h-4 mr-2" />
              Monthly Report
            </Button>

            <Button
              onClick={() => generateReport()}
              disabled={isLoading || isDataLoading}
              variant="outline"
              size="sm"
            >
              <RefreshCw className={`w-4 h-4 mr-2 ${isLoading ? 'animate-spin' : ''}`} />
              Refresh
            </Button>

            {reportData && (
              <Button
                onClick={downloadReport}
                variant="outline"
                size="sm"
              >
                <Download className="w-4 h-4 mr-2" />
                Download CSV
              </Button>
            )}

            <Button
              onClick={scheduleAutomatedReports}
              variant="outline"
              size="sm"
            >
              <Clock className="w-4 h-4 mr-2" />
              Schedule Auto-Reports
            </Button>
          </div>

            {lastGenerated && (
            <Badge variant="outline" className="text-xs">
              Last updated: {lastGenerated.toLocaleString()}
            </Badge>
          )}
        </CardContent>
      </Card>

      {/* Report Summary */}
      {reportData && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          
          <Card>
            <CardContent className="p-4">
              <div className="flex items-center gap-2">
                <Users className="w-5 h-5 text-blue-500" />
                <div>
                  <p className="text-sm text-gray-600">Total Employees</p>
                  <p className="text-2xl font-bold">{reportData.summary.total_employees}</p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-4">
              <div className="flex items-center gap-2">
                <Clock className="w-5 h-5 text-green-500" />
                <div>
                  <p className="text-sm text-gray-600">Total Hours</p>
                  <p className="text-2xl font-bold">{reportData.summary.total_hours_worked}h</p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-4">
              <div className="flex items-center gap-2">
                <TrendingUp className="w-5 h-5 text-purple-500" />
                <div>
                  <p className="text-sm text-gray-600">Avg Hours/Day</p>
                  <p className="text-2xl font-bold">{reportData.summary.average_hours_per_day}h</p>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-4">
              <div className="flex items-center gap-2">
                <FileText className="w-5 h-5 text-orange-500" />
                <div>
                  <p className="text-sm text-gray-600">Work Sessions</p>
                  <p className="text-2xl font-bold">{reportData.summary.total_work_sessions}</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      )}

      {/* Employee Performance */}
      {reportData && reportData.employee_breakdown.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Employee Performance</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {reportData.employee_breakdown.slice(0, 5).map((employee: any, index: number) => (
                <div key={index} className="flex items-center justify-between p-3 bg-gray-50 dark:bg-slate-800 rounded-lg">
                  <div>
                    <p className="font-medium">{employee.employee_name}</p>
                    <p className="text-sm text-gray-600">{employee.total_sessions} sessions</p>
                  </div>
                  <div className="text-right">
                    <p className="font-bold text-lg">{employee.total_hours}h</p>
                    <p className="text-sm text-gray-600">
                      {employee.average_session_duration.toFixed(1)}h avg
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Loading State */}
      {isLoading && (
        <Card>
          <CardContent className="p-8 text-center">
            <div className="flex items-center justify-center gap-2">
              <RefreshCw className="w-6 h-6 animate-spin text-blue-500" />
              <span>Generating {reportType} report...</span>
            </div>
          </CardContent>
        </Card>
      )}

      {!isLoading && !isDataLoading && reportData && reportData.summary.total_work_sessions === 0 && (
        <Card>
          <CardContent className="p-6 text-center text-sm text-muted-foreground">
            No completed time logs found in the selected period.
          </CardContent>
        </Card>
      )}
    </div>
  );
}
